### PR TITLE
Tape is a dev dependency

### PR DESCRIPTION
**Pull request by saebekassebil**
Found these modules after a looong search - cheers @tmpvar. `tape` is however only a `devDependency`.

### CODE REVIEW

**Comment by tmpvar** [comment]
oh, woops! can you not mod the version string? I'd prefer to use `npm version 1.0.1` instead

**Comment by saebekassebil** [comment]
Of course, feel free to squash - couldn't be bothered to _not_ do this in GitHub's edit.

**Comment by tmpvar** [comment]
thanks! published interval-add@1.0.1

**Comment by saebekassebil** [comment]
cheers!

**Pull request merged**
